using System.ComponentModel.DataAnnotations;

namespace NoteKeeper.Models
{
    /// <summary>
    /// Represents a note entity stored in the database.
    /// </summary>
    public class Note
    {
        [Key]
        public Guid NoteId { get; set; } = Guid.NewGuid(); // Unique identifier for the note

        [Required]
        [StringLength(60, ErrorMessage = "Summary must be between 1 and 60 characters.")]
        public string Summary { get; set; } = string.Empty; // Brief description of the note

        [Required]
        [StringLength(1024, ErrorMessage = "Details must be between 1 and 1024 characters.")]
        public string Details { get; set; } = string.Empty; // Full content of the note

        public DateTime CreatedDateUtc { get; set; } = DateTime.UtcNow; // Creation timestamp

        public DateTime? ModifiedDateUtc { get; set; } // Last modification timestamp, null if never updated

        public List<Tag> Tags { get; set; } = new List<Tag>(); // Associated tags, generated by AI
    }
}
